### ISSUE TITLE
redacted comments are not coming through Ticket sharing interface

### ISSUE THREAD

**Issue by Sarapulov** [zendesklabs/ticket_redaction_app#36]
Looks like redacted comments are not coming through Ticket sharing interface. Say, if you redact a comment on one ticket it doesn't get synced into a ticket linked via ticket sharing.

![screen shot 2015-02-10 at 10 25 25](https://cloud.githubusercontent.com/assets/1439823/6125560/3ea97c40-b10f-11e4-8f3b-58b4226bb0c6.png)

![screen shot 2015-02-10 at 10 25 43](https://cloud.githubusercontent.com/assets/1439823/6125559/3e9a0de6-b10f-11e4-9eb4-7142f8d2b9ef.png)

**Comment by dpawluk** [comment]
This is an issue that cannot be fixed at the app level. The sharing functionality would need an update.

**Comment by JamborJan** [comment]
The sharing feature seems to ignore updates. So the only thing you can do for know is install the app on both instances and remove comments / attachments 2 times. This is not nice but as far as I see Zendesk is not that quick with change requests and the chance that an update mechanism for the sharing feature will be introduced soon is rather low.
