### ISSUE TITLE
Text redaction fails after multiple redactions

### ISSUE THREAD

**Issue by lstrong** [zendesklabs/ticket_redaction_app#37]
I have a ticket with multiple rows that need to be redacted from the description text. First, the app doesn't work if I try to select multiple lines at the same time. So fine, I am doing line by line, but after I redact multiple times, I start getting a failure message. I refreshed the page, still failure. Gave it some time and then it worked again for another few more redactions, then failure once more.

**Comment by dpawluk** [comment]
This should handle multi-line redactions. I will look into this.

**Comment by dpawluk** [comment]
@lstrong,

I just finished redacting a whole paragraph of text all at once. Are you sure you are using the latest version, kept updated in the Zendesk Apps Marketplace?

![screen shot 2015-02-17 at 11 00 30 am](https://cloud.githubusercontent.com/assets/5264339/6232851/68293ada-b694-11e4-8904-c462e096b191.png)

**Comment by lstrong** [comment]
I installed the latest and now multiple line redaction works.

Thanks
-- 
Luciana Strong
VSI Solutions
469.519.2773 (o)
469.450.8899 (m)
lstrong@vsisolutions.com

From:  Daniel Pawluk <notifications@github.com>
Reply-To:  zendesklabs/ticket_redaction_app
<reply+00a79b86c0828b4f2f73019689e11b845299b0a9358c25e192cf0000000110fb362d9
2a169ce036de032@reply.github.com>
Date:  Tuesday, February 17, 2015 at 11:02 AM
To:  zendesklabs/ticket_redaction_app
<ticket_redaction_app@noreply.github.com>
Cc:  Luciana Strong <lstrong@vsisolutions.com>
Subject:  Re: [ticket_redaction_app] Text redaction fails after multiple
redactions (#37)


@lstrong <https://github.com/lstrong> ,

I just finished redacting a whole paragraph of text all at once. Are you
sure you are using the latest version, kept updated in the Zendesk Apps
Marketplace?

 <https://cloud.githubusercontent.com/assets/5264339/6232851/68293ada-b694-1
1e4-8904-c462e096b191.png>

‹
Reply to this email directly or view it on GitHub
<https://github.com/zendesklabs/ticket_redaction_app/issues/37#issuecomment-
74704645> .
