### ISSUE TITLE
Hide Interface While Redaction Isn't needed

### ISSUE THREAD

**Issue by dpawluk** [zendesklabs/ticket_redaction_app#41]
Feature request from customer, creating an issue

**Comment by YesThatAllen** [comment]
Backstory - we rarely want to redact text but often send attachments of trial versions of software.

Being able to redact those later will prevent old versions from being used later, so it'll be nice to save precious app space until we push a [Text] or [Attachment] button

**Comment by dpawluk** [comment]
@YesThatAllen, So there is a bigger bug right now that prevents subsequent redactions from being saved (only one at a time is redacted at the moment). I'll be investigating a patch to see if I can work around the bug until it is fixed. I'll also roll out a hide interface feature along with that future patch.

**Comment by YesThatAllen** [comment]
Interesting.. we have been using this plugin without issue since these issues were opened. If I see a time when I can't remove more than one item, I can let you know.

Meanwhile, I have been able to remove more than one attachment from a ticket (attachments are basically all I use this for)

**Comment by dpawluk** [comment]
Added to repo, submitting app update
