### ISSUE TITLE
clarify redacted.txt

### ISSUE THREAD

**Issue by YesThatAllen** [zendesklabs/ticket_redaction_app#42]
when removing an attachment.. I wonder why bother to leave "redacted.txt" as an attachment?

If it held the names of what was attached, that'd make explain it, i suppose, but I just downloaded and opened an empty file..

**Comment by dpawluk** [comment]
@YesThatAllen ,
This is actually functionality of the Zendesk API and not the App itself. Unfortunately, I don't have any control over this. You might want to drop a line over on the Zendesk [Product Feedback Forum](https://support.zendesk.com/hc/en-us/community/topics/200132066-Product-feedback). I'll go ahead and close this issue, sorry for the delay in getting you a response.

**Comment by YesThatAllen** [comment]
Thanks @dpawluk there are bigger fish to fry over in the forum ;-)
