### ISSUE TITLE
Role Permissions Issues

### ISSUE THREAD

**Issue by dhacker** [zendesklabs/ticket_redaction_app#47]
Permissions Problem? The app seems to only work for Administrators and does not work for Agents. This appears to be true regardless of what the settings are for "Role Permissions". For example. 

If I ENABLE Role Permissions I get two choices, Administrators and Agents. I check them both - the app only works for Administrators.

If I DISABLE Role Permissions the same thing happens. The app only works for Administrators and not Agents. 

Further expansion of our ZenDesk usage depends on this functionality so I would appreciate it if someone could take a look? Thanks.

**Comment by sandlerr** [comment]
Hi @dhacker thanks for opening this issue. Are you unable to even get the app to show up for your agents in the ticket sidebar or is it showing up but failing to redact?

**Comment by dpawluk** [comment]
@sandlerr it looks like the agent didn't have delete permissions. Closing this one out, thanks!
