### ISSUE TITLE
Arrow misplaced?

### ISSUE THREAD

**Issue by Jamman** [zendesklabs/ticket_redaction_app#54]
The minimise arrow seems to be misplaced and gets an odd border around it when clicked.

![image](https://cloud.githubusercontent.com/assets/3829792/26039213/0eababe8-396c-11e7-82c5-959007f44202.png)

**Comment by dpawluk** [comment]
@Jamman 

I appreciate the report. I think given the nature of the issue and that a V2 redaction app will be in the works relatively soon that we'll wait on fixing this. I appreciate the report and your time however, thanks!
