### ISSUE TITLE
One or more of the redactions failed...please try again

### ISSUE THREAD

**Issue by gunddere** [zendesklabs/ticket_redaction_app#59]
We are getting the error "One or more of the redactions failed...please try again" on some tickets when trying to redact passwords. We try again multiple times and it continues to fail. Is there any way this can be debugged to see what is causing the failure?

**Comment by mikeh89** [comment]
Hi there, getting the same error when redacting attachments. This only happens when the ticket is closed. Is there a reason this doesn't work for closed tickets?
@gunddere is this happening in closed tickets for you as well?

**Comment by tim-cotswold** [comment]
We are having the same issue. app uninstalled /zendesk refreshed/app re installed. The ticket we are trying to work on is currencly closed.

**Comment by gunddere** [comment]
I believe the redaction app actually edits tickets which is why it is failing for you guys on a closed ticket as a closed ticket cannot be edited. You may be able to change the status from closed to an editable status such as solved using the API and then use the redaction app.

I just figured out my problem yesterday. The tickets that the redaction is failing on are in solved status which is being set by a trigger we have set up after the ticket is in pending status for 7 days. On these particular tickets, there are required fields that aren't populated when the ticket is set to pending. Normally you wouldn't be able to manually set these to solved without the required fields being populated, but using the trigger feature, the ticket gets set to solved with the required field being empty. When redacting the ticket I am guessing it fails due to an exception being thrown by zendesk in regard to the ticket being in solved status with the required fields being empty. To correct the problem, I just had to populate the required fields and the redaction then worked properly. Hope this helps.
