### ISSUE TITLE
App permissions structure not working 

### ISSUE THREAD

**Issue by bodenlinden** [zendesklabs/ticket_redaction_app#61]
Agents who belong to the correct group are still receiving a permissions error.

![pasted_image_at_2017_08_15_04_26_pm_360](https://user-images.githubusercontent.com/23083136/29340964-982cee06-81d6-11e7-9419-5bf669dba03d.png)

**Comment by dschutz** [comment]
We are experiencing this same issue, but only admins can use the Ticket Redaction plug-in. Any non-admins see the permissions error. This happens regardless of what is checked under the **Role restrictions** settings.

**Comment by dpawluk** [comment]
@dschutz and @bodenlinden are you 100% sure the users who get this notice have permission to delete tickets. From the error message that seems to be the main issue. The ability to delete tickets is necessary to use the redaction endpoints and in turn the app.

**Comment by dschutz** [comment]
The ability to delete tickets had been switched off for all our agents. Not sure when or how that happened, but it appeared to be done without our interaction. After turning that back on, redaction works again.

**Comment by dpawluk** [comment]
@dschutz great to hear this is working for you again. I'll go ahead and close the issue since from the app's perspective it appears everything was working normally.
