### ISSUE TITLE
Problem with roles

### ISSUE THREAD

**Issue by Bacarden** [zendesklabs/ticket_redaction_app#66]
Am I misunderstanding something or is there an issue with the tool when my role is not administrator?

I keep getting this: "Unfortunately your role does not have access to redaction. Your administrator can change your role to allow 'ticket deletion' and enable this app
Get Support"

.. even when I chose "no role limitations" in the installation or I edit it afterwards it doesn't allow me to modify as any other but the administrator role?

**Comment by dpawluk** [comment]
In order to redact a user is required to be able to delete tickets, this has nothing to do with app role restrictions. The error message should explain how to fix this.
