### ISSUE TITLE
Redacting Images on a closed ticket

### ISSUE THREAD

**Issue by bwest5280** [zendesklabs/ticket_redaction_app#68]
Hey I need to clear out some images of a customers' IDs that we didn't want sent to us in the first place but it doesn't seem to do that on our closed tickets. Is there a work around?

**Comment by bwest5280** [comment]
Also having an issue redacting an image on an open ticket. It's an image but not an attachment. Please help!

**Comment by dpawluk** [comment]
@bwest5280  
-1 This is a limitation imposed by Zendesk. Closed tickets cannot be edited in any way. If you have to get rid of the information the only way is to delete said ticket.
-2 As for the open ticket problem, for now the only way to do this is to redact the source html link to the image. V2 will attempt to fix this if Zendesk provides a way to individual redact inline images. I wish there was a way to help with these but the way Zendesk currently works it is impossible to achieve a redaction with this via the API (which is what the App uses to perform redactions).
