### ISSUE TITLE
Redaction app unable to find comment string it contains a space followed by a return

### ISSUE THREAD

**Issue by claudelj** [zendesklabs/ticket_redaction_app#70]
When a comment string is contains a space followed by return the app will return that the that string is found in 0 comments.  The space & return can be anywhere within the comment and it will cause the entire string to not be found.

![image](https://user-images.githubusercontent.com/29108532/35350612-5261f6f4-00f3-11e8-8618-fa663f125919.png)

**Comment by dpawluk** [comment]
@claudelj thanks for the feedback. Since this can be worked around (albeit with some hassle) in the current version I'll hold off fixing this for the V2 version coming out in March. Thanks for the feedback!
