### ISSUE TITLE
Redaction app does not redact text or numbers anymore

### ISSUE THREAD

**Issue by jjmalfant** [zendesklabs/ticket_redaction_app#71]
Hi there,

We have been using your app for over 2 years now without any issues but since last week we have noticed that the application does not redact our text anymore, did you do any recent update?

The application recognise the text to redact example:

"Do you wish to redact the below text?
Note: This will remove the below text, which occurs in 2 comments on this ticket. This change is permanent and cannot be undone."

But when clicked "Yes, redact the above text" the application crash or does not redact anything. It sometimes works after clicking 10 times the "Yes, redact the above text" button but does it very unreliably. 

We have tried  refreshing the apps, use different web browser or different computers but the issue still remain, the redaction does not happen at all or does not happen on the first click.

The application does not do it's main feature anymore, redacting text or numbers. Can this be please looked into? 

We use this application to hide sensitive information for security reasons.

Thanks in advance to prioritise this issue.

Regards,
JJM

**Comment by dpawluk** [comment]
@jjmalfant it seems like some background work on how tickets are processed prevents the second redaction, so the term might have to be redacted once per each time. Are you refreshing the whole page after making the redaction?

**Comment by jjmalfant** [comment]
@dpawluk Thanks for the help, refreshing the page does help a bit. It seems to be overall slower for the app to find the text and hide it since the new update. We can live with it for now and keep trying by refreshing and redacting the text again. It would still be worth improving this app and it's processing time to avoid refreshing the page for each redaction.

**Comment by dpawluk** [comment]
@jjmalfant unfortunately I wrote and maintain this app as a hobby in my free time. If its okay I'm going to leave the V1 version how it is. I'm currently working on a V2 version to be out in a month or so and I can make sure to fix it there. Does that sound workable?

**Comment by jjmalfant** [comment]
@dpawluk No problem, thanks for the help and your honest reply. We can work with V1 and wait until V2 comes out in a month.

**Comment by dpawluk** [comment]
Thanks @jjmalfant, if you have any good ideas for the app or added features let me know, now is definitely the time ;) please make a separate issue for any other feedback though so I can organize everything easier, thanks!
