### ISSUE TITLE
Unsupported characters?

### ISSUE THREAD

**Issue by FridtjofHals** [zendesklabs/ticket_redaction_app#73]
Hi.

I found a character that I was not able to redact:  '
It was part of a string of text, and the initial screen show it found 1 occurence of the complete string. But when clicking 'Yes, redact...'-button, I was given an error that it did not work. Tried to redact everything before the ' and that workd, clicked F5, and then tried to redact everything after the ' and that worked also.

Do you happpen to have a list of characters that are not supported?
Is there any plan to add more characters to the redaction app?

**Comment by dpawluk** [comment]
@FridtjofHals 
If you have rich text enabled almost any character outside of the ASCII range will fail to redact. The redaction feature was released before rich-text was supported. I recommend creating a ticket with Zendesk and asking for redaction to support rich-text. Thanks!
