### ISSUE TITLE
Redaction does not work for HTML email...

### ISSUE THREAD

**Issue by hightidetech** [zendesklabs/ticket_redaction_app#75]
I noticed this behavior for a ticket that was created through the Zendesk Help Center where an update contained a block of HTML that is not redacted in the associated email with the comment update.  
<img width="717" alt="html_redacted_snippet" src="https://user-images.githubusercontent.com/22894553/36289322-488f94aa-1274-11e8-9ee4-3f8474464f06.png">

<img width="713" alt="text_redaction_snipet" src="https://user-images.githubusercontent.com/22894553/36289341-676a3ee8-1274-11e8-8a67-acdbddd4a263.png">

The only workaround seems to be to delete the entire ticket.

**Comment by hightidetech** [comment]
Note, this same problem happens for inline images

**Comment by dpawluk** [comment]
This is a limitation with the endpoint, and as the app is just a vehicle for the endpoint this needs to be addressed with Zendesk directly. I would avoid mentioning the app and create a ticket that mentions the endpoint is behaving like this. Same with inline attachments. I wish I could help but I only work on this app and the endpoint behavior is out of my hands.
